Do not run 'Build pages' when 'Update logs' is failed

diff --git a/.github/workflows/update_logs.yml b/.github/workflows/update_logs.yml
--- a/.github/workflows/update_logs.yml
+++ b/.github/workflows/update_logs.yml
@@ -49,7 +49,7 @@ jobs:
           git add --all --intent-to-add --force
           if git diff --exit-code --quiet; then
             echo 'Nothing to update.'
-            exit 0
+            exit 1  # Make fail to avoid triggering 'Build pages' workflow
           fi
           git config user.email "slacklog@vim-jp.org"
           git config user.name "Slack Log Generator"
